### ISSUE TITLE
Planning material

### ISSUE THREAD

**Issue by karthik** [karthik/esa_data_viz#1]
Hi @naupaka @atredennick,
We should start making a rough plan for the workshop. I heard that there will be no wifi this year so we'll need to plan ahead. We can ask people to install `ggplot2` + dependencies and clone this repo the day before (from their hotel or elsewhere). We should also plan to bring copies of the material (code + slides + ggplot2 binaries and source) on a flash drive.

As for material, I recently taught a 2 hr grad seminar and put together some material we can reuse/repurpose for ESA. 
- [repo is here](https://github.com/karthikram/ggplot-lecture)
- [slides](https://speakerdeck.com/karthik/introduction-to-ggplot2)

Thoughts?

**Comment by ramnathv** [comment]
I am experimenting with a way to bring live coding to presentation slides using [Slidify](http://slidify.org) and [Shiny](http://github.com/rstudio/shiny). Here is a prototype on github that you can run using

``` coffee
shiny::runUrl('https://github.com/ramnathv/InteractiveSlides/archive/master.zip')
```

Here are some of the features:
1. It minimizes switching between the R console and the slides.
2. You can prepopulate code in the text area.
3. You can add exercises, providing hints.

If you guys are interested, I can work with you to create an interactive version of the tutorial for ggplot2.

**Comment by karthik** [comment]
That would be fantastic! We're definitely interested. Thank you. I've experimented myself (before Shiny came around) but couldn't get it to work smoothly.

**Comment by ramnathv** [comment]
Great! Let me create a new repo for this, and add some of the slides from your ggplot2 lecture. The markup is reasonably simple (but can be simplified even further, and I am working on it). You can fork the repo and add the other slides. Let me know if this works.

Alternately, you might want to create the repo yourself and I can fork it and  issue pull requests.

**Comment by karthik** [comment]
Since room will not have any wi-fi, we'll hold off on this format for a future workshop.
