### ISSUE TITLE
Stickies

### ISSUE THREAD

**Issue by atredennick** [karthik/esa_data_viz#2]
Do you guys know how Software Carpentry uses stickies? Is it red and green, with red meaning they need help, green meaning they are done with the exercise, and no stikie meaning they are working? I'll pick some up if you all think it would be helpful.

**Comment by karthik** [comment]
Yes. Red = help, green = Done with current exercise. Although colors don't really matter too much. Just as long as we agree on a scheme and have two diff colors.

I can pick some up too.

**Comment by atredennick** [comment]
Acquired on all fronts.
