### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by atredennick** [karthik/esa_data_viz#3]
Hey @karthikram and @naupaka,

I am going to add some more examples today/tomorrow. 1) The example using Peter Adler's data, but with cleaned up data so it will be easier to work with; 2) A scatterplot example from my PLoS ONE paper; and 3) some example of grouped barplots with error bars (possibly with just fake data).

Any other examples you think we should have on hand.

**Comment by karthik** [comment]
I think we should be set with the material we've got once you add this. Easily fills two hours. And then we can leave folks with the last hour free to work on their own material.

**Comment by atredennick** [comment]
I was putting these examples together for folks that don't have their own material (i.e., for the last hour). Is that still the plan?

**Comment by karthik** [comment]
Sure thing. So far everyone is bringing their own data to play with.

**Comment by atredennick** [comment]
OK, examples all done. I think this will serve as nice example if anyone wants to use this as an online resource. Likewise, during the workshop people can borrow snippets of code from these examples as necessary.
