### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by atredennick** [karthik/esa_data_viz#4]
What is the plan for packages needed? For the lecture part it looks like they'll need `ggplot2`, `plyr`, `reshape2`, and `ggthemes`. If they want to use bits of code from my examples they may need some others as well (like `gridExtra` for arranging plots). Should we send out an R script with just a bunch of `install.package()` lines for them to run before showing up?

**Comment by karthik** [comment]
I added all the relevant packages we'll need to the README.
