### ISSUE TITLE
A tentative schedule

### ISSUE THREAD

**Issue by karthik** [karthik/esa_data_viz#5]
We have 3 hours. Just so we have rough schedule:
- [ ] A quick introduction + installation issues (15 minutes)
- [ ] Basics of ggplot (**go through that introductory material I wrote before**) (45 minutes)
- [ ] Break (15 minutes)
- [ ] Finish intro material + advanced graphing techniques (45 minutes)
- [ ] Free form. We walk around and help folks (40 minutes)
- [ ] Wrap up and summaries (20 minutes) (Have people tell us what worked and what didn't. What are remaining challenges. And maybe a little show and tell if they did make something cool in that last hour).

thoughts?

**Comment by naupaka** [comment]
Sounds good.  Do we need slides or anything for the advanced techniques section, or will we just go through that live on the projector?

Should we come up with some sort of evaluation sheet/form/survey to capture comments/suggestions at the end?

**Comment by karthik** [comment]
For the advanced part I think a live coding exercise would be great. Seems like @atredennick threw a few of his personal examples in. and we can show others. One computer can be hard wired so if we need anything web related, it's totally doable.

For Software Carpentry we just do an open etherpad. People in the room enter one good, one bad thing and we quickly discuss it. Might be hard here given that no one will have wifi. I could write up a post workshop email assessment and mail that around (another <1 minute form).

**Comment by naupaka** [comment]
Slides (re)done for the intro bit.  Excited for Sunday!

**Comment by karthik** [comment]
Fantastic! The edits look great. Looking forward to it too. I'll leave this issue open in case we want to edit the schedule further.

**Comment by atredennick** [comment]
Thanks for putting the slides together guys. Looks great. When you refer to advanced graphing techniques, is it just stuff beyond the basic ggplot() + geom_ofchoice() combo?

**Comment by naupaka** [comment]
My thought was just that the 'advanced techniques' are just more in-depth examples, plus helping people with custom requests, etc.

**Comment by naupaka** [comment]
Nice mapping addition!

**Comment by karthik** [comment]
Thanks! I think we're ready :shipit: 
Might make some last minute changes, clarify code, add more comments etc.
@naupaka Can you send out a link to the repo by tomorrow am? Otherwise I'll do it. Just putting it so we don't forget.

**Comment by naupaka** [comment]
@karthikram sure thing.  I will hold off till first thing tomorrow morning in case any other changes trickle in from you or @atredennick , then I'll send out link and brief logistic pointers in an email to the course + both of you.

**Comment by atredennick** [comment]
I'm in Salt Lake with no Internet access through tomorrow morning, so I won't be able to add anything else. Still might work up a transparent line spaghetti plot though for fun because they look cool. Can add it to the repo for posterity later. 

Thanks for organizing the examples Khartik!

-Andrew
via my phone

**Comment by karthik** [comment]
wow, thanks @naupaka

**Comment by naupaka** [comment]
@karthik tidying my unresolved issue backlog, this one's only 9 years late
