### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by karthik** [karthik/esa_data_viz#6]
Most of the examples posted in `Examples` have a few issues.

Too many files and versions nested in directories. Can be simplified with just a single markdown script instead of nested folders.

data reference local paths on Andrew's computer.

Functions used are now deprecated in recent versions of `ggplot2`. Since we're asking folks to do a fresh install (and I'm also on the latest version, this needs to get updated.

Todos
- [x] Simplify file structure
- [x] Fix paths
- [x] Fix deprecated ggplot functions

**Comment by naupaka** [comment]
I'm about to get on a flight but I can work on the paths and file structure.  Might need the internet for function updates?

**Comment by karthik** [comment]
Don't do anything on the plane. I'll fix for now and drop you a note.

**Comment by naupaka** [comment]
Roger that.

**Comment by karthik** [comment]
With commit [a646651f4b473e91d1788cdfcf2b4483f8dc1e89](https://github.com/karthikram/esa_data_viz/commit/a646651f4b473e91d1788cdfcf2b4483f8dc1e89) I have folded all examples into one markdown file for easier navigation. Also fixed code errors and renamed folders for readability.
